"""In-app help window.

Loads the pre-built data/help.html (generated by scripts/build_help.py) into
a WebKit view.  Falls back to a formatted TextBuffer view when WebKit is not
available.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

import gi
gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
gi.require_version("Gdk", "4.0")
from gi.repository import Adw, Gdk, Gtk

from .auth_dialog import WebKit, WEBKIT_AVAILABLE

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# File location helpers
# ---------------------------------------------------------------------------

def _find_help_html() -> Path | None:
    """Locate the pre-built help.html file, rebuilding it in dev if stale."""
    candidates = [
        Path(__file__).resolve().parent.parent.parent.parent / "data" / "help.html",
        Path("/app/share/doc/com.seravault.cloudsync/help.html"),
    ]
    for p in candidates:
        if p.is_file():
            # In the source tree, rebuild if user-guide.md is newer than help.html
            src_md = p.parent / "docs" / "user-guide.md"
            if src_md.is_file() and src_md.stat().st_mtime > p.stat().st_mtime:
                _rebuild_help(p.parent.parent)
            return p
    # Not found — try to build it now (dev source tree only)
    src_root = Path(__file__).resolve().parent.parent.parent.parent
    if (src_root / "scripts" / "build_help.py").is_file():
        _rebuild_help(src_root)
        out = src_root / "data" / "help.html"
        if out.is_file():
            return out
    return None


def _rebuild_help(src_root: Path) -> None:
    """Run scripts/build_help.py from the given source root."""
    import subprocess, sys
    script = src_root / "scripts" / "build_help.py"
    try:
        subprocess.run([sys.executable, str(script)], check=True, cwd=src_root,
                       capture_output=True)
        log.debug("Rebuilt data/help.html")
    except Exception as exc:
        log.warning("Could not rebuild help.html: %s", exc)


def _find_readme() -> Path | None:
    """Locate user-guide.md (used by the plain-text fallback)."""
    candidates = [
        Path(__file__).resolve().parent.parent.parent.parent / "data" / "docs" / "user-guide.md",
        Path("/app/share/doc/com.seravault.cloudsync/user-guide.md"),
    ]
    for p in candidates:
        if p.is_file():
            return p
    return None



# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# TextBuffer renderer (WebKit fallback)
# ---------------------------------------------------------------------------

def _fill_text_buffer(buf: Gtk.TextBuffer, text: str) -> None:
    """Render markdown into a TextBuffer using formatting tags."""
    h1_tag  = buf.create_tag("h1",  weight=700, scale=1.6, pixels_below_lines=6, pixels_above_lines=8)
    h2_tag  = buf.create_tag("h2",  weight=700, scale=1.3, pixels_below_lines=4, pixels_above_lines=6)
    h3_tag  = buf.create_tag("h3",  weight=700, scale=1.1, pixels_below_lines=2, pixels_above_lines=4)
    code_tag  = buf.create_tag("code_inline", family="monospace", scale=0.88)
    block_tag = buf.create_tag("code_block",  family="monospace", scale=0.86,
                               left_margin=24, right_margin=24,
                               pixels_above_lines=6, pixels_below_lines=6)
    bold_tag  = buf.create_tag("bold",  weight=700)
    dim_tag   = buf.create_tag("hr_dim", foreground="#999999")
    table_tag = buf.create_tag("table", family="monospace", scale=0.88)

    def ins(t: str, *tags) -> None:
        it = buf.get_end_iter()
        active = [tg for tg in tags if tg is not None]
        if active:
            buf.insert_with_tags(it, t, *active)
        else:
            buf.insert(it, t)

    def ins_inline(t: str, extra: "Gtk.TextTag | None" = None) -> None:
        for part in re.split(r"(`[^`]+`)", t):
            if part.startswith("`") and part.endswith("`") and len(part) > 1:
                ins(part[1:-1], code_tag, extra)
            else:
                for seg in re.split(r"(\*\*[^*]+\*\*)", part):
                    m = re.match(r"\*\*([^*]+)\*\*", seg)
                    if m:
                        ins(m.group(1), bold_tag, extra)
                    else:
                        clean = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", seg)
                        ins(clean, extra)

    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]

        # Fenced code block
        if line.startswith("```"):
            i += 1
            code_lines: list[str] = []
            while i < len(lines) and not lines[i].startswith("```"):
                code_lines.append(lines[i])
                i += 1
            ins("\n".join(code_lines) + "\n", block_tag)
            i += 1
            continue

        # HR
        if re.fullmatch(r"-{3,}", line.strip()):
            ins("─" * 64 + "\n", dim_tag)
            i += 1
            continue

        # Heading
        m = re.match(r"(#{1,3}) (.*)", line)
        if m:
            tag = [h1_tag, h2_tag, h3_tag][len(m.group(1)) - 1]
            ins(m.group(2) + "\n", tag)
            i += 1
            continue

        # Table separator row — skip
        if re.match(r"^\s*\|[-| :]+\|\s*$", line):
            i += 1
            continue

        # Table data row
        if "|" in line and line.strip().startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            ins("  " + "   │   ".join(cells) + "\n", table_tag)
            i += 1
            continue

        # Bullet list
        m = re.match(r"^[-*] (.*)", line)
        if m:
            ins("  • ", bold_tag)
            ins_inline(m.group(1))
            ins("\n")
            i += 1
            continue

        # Blank line
        if line.strip() == "":
            ins("\n")
            i += 1
            continue

        # Paragraph
        ins_inline(line)
        ins("\n")
        i += 1


# ---------------------------------------------------------------------------
# Help window
# ---------------------------------------------------------------------------

class HelpWindow(Adw.Window):
    """A non-modal window that renders README.md as HTML via WebKit."""

    def __init__(self, parent: Gtk.Window) -> None:
        super().__init__(
            title="CloudSync Help",
            transient_for=parent,
            default_width=880,
            default_height=720,
            resizable=True,
        )

        toolbar_view = Adw.ToolbarView()

        # --- Header bar with search toggle ---
        header = Adw.HeaderBar()
        search_btn = Gtk.ToggleButton(
            icon_name="system-search-symbolic",
            tooltip_text="Search (Ctrl+F)",
        )
        header.pack_end(search_btn)
        toolbar_view.add_top_bar(header)

        # Keyboard shortcut: Ctrl+F toggles search
        ctrl = Gtk.ShortcutController(scope=Gtk.ShortcutScope.LOCAL)
        ctrl.add_shortcut(Gtk.Shortcut(
            trigger=Gtk.KeyvalTrigger.new(ord("f"), Gdk.ModifierType.CONTROL_MASK),
            action=Gtk.CallbackAction.new(lambda *_: search_btn.set_active(not search_btn.get_active()) or True),
        ))
        self.add_controller(ctrl)

        # --- Locate content ---
        # WebKit path: load the pre-built help.html via file:// URI.
        # Text fallback: load README.md and render with _fill_text_buffer.
        readme = _find_readme()
        if readme:
            try:
                content = readme.read_text(encoding="utf-8")
            except OSError as exc:
                log.warning("Could not read README.md: %s", exc)
                content = "# Help\n\nCould not load README.md."
        else:
            content = "# Help\n\nREADME.md not found."

        help_html = _find_help_html()

        _use_webkit = False
        if WEBKIT_AVAILABLE and help_html:
            try:
                web = WebKit.WebView()
                web.set_hexpand(True)
                web.set_vexpand(True)
                web.load_uri(help_html.as_uri())
                _use_webkit = True
            except Exception as exc:
                log.warning("WebKit failed, falling back to text view: %s", exc)

        if _use_webkit:
            find_controller = web.get_find_controller()
            _FIND_OPTS = (
                WebKit.FindOptions.CASE_INSENSITIVE
                | WebKit.FindOptions.WRAP_AROUND
            )

            # --- Search bar (WebKit path) ---
            search_bar = Gtk.SearchBar(show_close_button=False)
            search_entry = Gtk.SearchEntry(
                placeholder_text="Search…",
                hexpand=True,
                max_width_chars=40,
            )
            prev_btn = Gtk.Button(icon_name="go-up-symbolic", tooltip_text="Previous")
            prev_btn.add_css_class("flat")
            next_btn = Gtk.Button(icon_name="go-down-symbolic", tooltip_text="Next")
            next_btn.add_css_class("flat")

            search_box = Gtk.Box(spacing=4)
            search_box.append(search_entry)
            search_box.append(prev_btn)
            search_box.append(next_btn)
            search_bar.set_child(search_box)

            def _do_search(*_):
                text = search_entry.get_text()
                if text:
                    find_controller.search(text, _FIND_OPTS, 1000)
                else:
                    find_controller.search_finish()

            def _on_search_bar_toggled(btn):
                active = btn.get_active()
                search_bar.set_search_mode(active)
                if active:
                    search_entry.grab_focus()
                else:
                    find_controller.search_finish()
                    search_entry.set_text("")

            search_entry.connect("search-changed", _do_search)
            prev_btn.connect("clicked", lambda _: find_controller.search_previous())
            next_btn.connect("clicked", lambda _: find_controller.search_next())
            search_entry.connect("activate", lambda _: find_controller.search_next())
            search_btn.connect("toggled", _on_search_bar_toggled)

            # Wrap WebView + search bar in a vertical box
            content_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
            content_box.append(search_bar)
            content_box.append(web)
            toolbar_view.set_content(content_box)

        else:
            # --- Fallback: formatted TextBuffer view ---
            buf = Gtk.TextBuffer()
            _fill_text_buffer(buf, content)
            highlight_tag = buf.create_tag("search-highlight", background="yellow", foreground="black")

            tv = Gtk.TextView(
                buffer=buf,
                editable=False,
                wrap_mode=Gtk.WrapMode.WORD,
                top_margin=16,
                left_margin=20,
                right_margin=20,
                bottom_margin=16,
            )
            scroll = Gtk.ScrolledWindow(
                hscrollbar_policy=Gtk.PolicyType.NEVER,
                vexpand=True,
            )
            scroll.set_child(tv)

            # Search bar (plain-text fallback)
            search_bar = Gtk.SearchBar(show_close_button=False)
            search_entry = Gtk.SearchEntry(
                placeholder_text="Search…",
                hexpand=True,
                max_width_chars=40,
            )
            prev_btn = Gtk.Button(icon_name="go-up-symbolic", tooltip_text="Previous")
            prev_btn.add_css_class("flat")
            next_btn = Gtk.Button(icon_name="go-down-symbolic", tooltip_text="Next")
            next_btn.add_css_class("flat")

            search_box = Gtk.Box(spacing=4)
            search_box.append(search_entry)
            search_box.append(prev_btn)
            search_box.append(next_btn)
            search_bar.set_child(search_box)

            self._plain_matches: list = []
            self._plain_match_idx: int = -1

            def _plain_search(*_):
                buf.remove_tag(highlight_tag, buf.get_start_iter(), buf.get_end_iter())
                self._plain_matches = []
                self._plain_match_idx = -1
                text = search_entry.get_text().lower()
                if not text:
                    return
                start = buf.get_start_iter()
                while True:
                    found = start.forward_search(
                        text, Gtk.TextSearchFlags.CASE_INSENSITIVE, None
                    )
                    if not found:
                        break
                    match_start, match_end = found
                    buf.apply_tag(highlight_tag, match_start, match_end)
                    self._plain_matches.append(buf.create_mark(None, match_start, True))
                    start = match_end
                if self._plain_matches:
                    _plain_jump(0)

            def _plain_jump(idx: int):
                if not self._plain_matches:
                    return
                self._plain_match_idx = idx % len(self._plain_matches)
                mark = self._plain_matches[self._plain_match_idx]
                it = buf.get_iter_at_mark(mark)
                tv.scroll_to_iter(it, 0.1, True, 0.0, 0.3)

            def _on_search_bar_toggled(btn):
                active = btn.get_active()
                search_bar.set_search_mode(active)
                if active:
                    search_entry.grab_focus()
                else:
                    buf.remove_tag(highlight_tag, buf.get_start_iter(), buf.get_end_iter())
                    search_entry.set_text("")

            search_entry.connect("search-changed", _plain_search)
            prev_btn.connect("clicked", lambda _: _plain_jump(self._plain_match_idx - 1))
            next_btn.connect("clicked", lambda _: _plain_jump(self._plain_match_idx + 1))
            search_entry.connect("activate", lambda _: _plain_jump(self._plain_match_idx + 1))
            search_btn.connect("toggled", _on_search_bar_toggled)

            content_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
            content_box.append(search_bar)
            content_box.append(scroll)
            toolbar_view.set_content(content_box)

        self.set_content(toolbar_view)
